algoritmo "semnome"
// Função :
// Autor :
// Data : 22/11/2024
// Seção de Declarações 
var
   valor1, valor2, media : real
inicio
// Seção de Comandos 
   Escreval(" digite o primeiro valor ")
   Leia(valor1)
   Escreval(" digite o segundo valor ")
   Leia(valor2)
   media <- (valor1 + valor2)/2
   Escreval("o resultado da média entre ", valor1, " e ", valor2, " é", media)
fimalgoritmo
