algoritmo "aula2"
// Função :
// Autor :
// Data : 21/11/2024
// Seção de Declarações 
var
   valor1, valor2, soma : Inteiro
inicio
   // Seção de Comandos
   Escreval("digite o primeiro valor: ")
   Leia(valor1)
   Escreval("digite o segundo valor: ")
   Leia(valor2)
   
   soma <- valor1 + valor2
   
   Escreval("o resultado da soma entre ", valor1, " e ", valor2, " é ", soma)
fimalgoritmo
